theme = "tokyonight"

[editor]
scrolloff = 15
mouse = false
completion-timeout = 5
preview-completion-insert = false
completion-replace = true
true-color = true
bufferline = "multiple"
color-modes = true
popup-border = "all"

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "underline"

[editor.file-picker]
hidden = false

[editor.inline-diagnostics]
cursor-line = "hint"

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
a = ["append_mode", "collapse_selection"]
i = ["insert_mode", "collapse_selection"]
'=' = [":format"]

[keys.insert]
C-space = "completion"
