theme = "tokyonight"

[editor]
scrolloff = 15
mouse = false
completion-timeout = 0
completion-trigger-len = 1
completion-replace = true
true-color = true
bufferline = "multiple"
color-modes = true

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "underline"

[editor.file-picker]
hidden = false

[editor.smart-tab]
enable = false

[keys.normal]
C-space = {f = ":format", n = ":new", c = ":bc", w = ":w", q = ":q", x = ":q!"}
A-h = ":bp"
A-l = ":bn"
esc = ["collapse_selection", "keep_primary_selection"]

[keys.insert]
C-space = "completion"
