theme = "kanagawa"

[editor]
scrolloff = 15
mouse = false
completion-timeout = 5
preview-completion-insert = false
completion-trigger-len = 1
completion-replace = true
true-color = true
bufferline = "multiple"
color-modes = true
end-of-line-diagnostics = "hint"

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "underline"

[editor.file-picker]
hidden = false

[editor.smart-tab]
enable = false

[editor.inline-diagnostics]
cursor-line = "error"

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
a = ["append_mode", "collapse_selection"]
i = ["insert_mode", "collapse_selection"]

[keys.insert]
C-space = "completion"
